### ISSUE TITLE
使用自定义view时，页数为三时，右滑崩溃

### ISSUE THREAD

**Issue by HappySKT** [why168/LoopViewPagerLayout#4]

**Comment by why168** [comment]
#### 兄弟，我测试了没有出现崩溃啊！
#### 你是怎么使用的呢？崩溃的日志发上来看看。 @HappySKT

**Comment by HappySKT** [comment]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                                   at android.view.ViewGroup.addViewInner(ViewGroup.java:4438)
                                                                                   at android.view.ViewGroup.addView(ViewGroup.java:4274)
                                                                                   at android.support.v4.view.ViewPager.addView(ViewPager.java:1505)
                                                                                   at android.view.ViewGroup.addView(ViewGroup.java:4215)
                                                                                   at android.view.ViewGroup.addView(ViewGroup.java:4188)
                                                                                   at com.project.zpd.viewpagettest.com.viewpager.MyViewAdapter.instantiateItem(MyViewAdapter.java:44)
                                                                                   at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1034)
                                                                                   at android.support.v4.view.ViewPager.populate(ViewPager.java:1216)
                                                                                   at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                                   at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2150)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2143)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)

**Comment by why168** [comment]
#### 你的自定义View写得有问题吧。
#### 每次先removeAllViews();后再addView();

**Comment by HappySKT** [comment]
是在adapter里面removeallviews吗

**Comment by HappySKT** [comment]
为什么只有页数为3时有这个问题，其他页数都没问题

**Comment by why168** [comment]
### 你自定义View出了问题，我给你解决，方便把代码发我邮箱吗？
### edwin.wu05@gmail.com

**Comment by HappySKT** [comment]
public class MyView extends FrameLayout {

    TextView textView,textView1,textView2;
    public MyView(@NonNull Context context) {
        super(context);
        init(context);
    }

    public MyView(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
        init(context);
    }

    
    public MyView(@NonNull Context context, @Nullable AttributeSet attrs, @AttrRes int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }
    public void setTextView(String text){
        textView.setText(text+"");
        textView1.setText(text+"");
        textView2.setText(text+"");
    }

    private void init(Context context){
        LayoutInflater.from(context).inflate(R.layout.first_view,this);
        textView = (TextView) findViewById(R.id.text_1);
        textView1 = (TextView) findViewById(R.id.text_2);
        textView2 = (TextView) findViewById(R.id.text_3);
        setTextView("dddddddddddddddddd");
    }
}
这个是我的自定义view 麻烦看一下有问题吗

**Comment by why168** [comment]
你发这个我怎么看？
整个项目发给我或者你的代码是怎么写的呢？
全部贴上来。

**Comment by HappySKT** [comment]
public class MyViewAdapter extends PagerAdapter {

    List<View> mDatas;
    View.OnClickListener clickListener;
    UpdateDatasLIstener lIstener;
    public MyViewAdapter(List<View> mDatas,UpdateDatasLIstener lIstener,View.OnClickListener clickListener) {
        this.mDatas = mDatas;
        this.lIstener = lIstener;
        this.clickListener =clickListener;
    }

    @Override
    public int getCount() {
        return Short.MAX_VALUE;
    }

    @Override
    public boolean isViewFromObject(View view, Object object) {
        return view == object;
    }

    @Override
    public void destroyItem(ViewGroup container, int position, Object object) {
        container.removeView((View)object);
    }

    @Override
    public Object instantiateItem(ViewGroup container, int position) {

        int index = position%mDatas.size();
        View view = lIstener.updateData(index);
        container.addView(view);
        return view;
    }
}



public class MainFragment extends Fragment implements UpdateDatasLIstener ,View.OnClickListener{


    ViewPagerLayout viewPagerLayout;
    List<View> mDatas;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

        return inflater.inflate(activity_main,container,false);
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        viewPagerLayout = (ViewPagerLayout) view.findViewById(R.id.view_pager);
        viewPagerLayout.setLoop_ms(5000);//轮播的速度(毫秒)
        viewPagerLayout.setLoop_duration(5000);//滑动的速率(毫秒)
        viewPagerLayout.setLoop_style(LoopStyle.Empty);//轮播的样式-默认empty
        viewPagerLayout.setIndicatorLocation(IndicatorLocation.Center);//指示器位置-中Center
        viewPagerLayout.initializeData(getActivity());//初始化数据
       mDatas = new ArrayList<>();
        mDatas.add(new MyView(getContext()));
        mDatas.add(new MyView(getContext()));
        mDatas.add(new MyView(getContext()));
        viewPagerLayout.setLoopData(mDatas,this,this);
        Log.d("", "onViewCreated: "+Integer.MAX_VALUE);
    }


    @Override
    public void onStart() {
        super.onStart();
        viewPagerLayout.startLoop();
    }

    @Override
    public void onStop() {
        super.onStop();
        viewPagerLayout.stopLoop();
    }}



整个项目加密了  所以没法发全部  不好意思  这个是代码  麻烦看看

**Comment by why168** [comment]
这样吧！你新建一个项目把你自定义的代码写进入，打包发给我。
我给你解决bug

**Comment by why168** [comment]
loopViewPager.setCurrentItem(index);

设置了吧？

**Comment by HappySKT** [comment]
只要是Android项目都加密了  发出去也是乱码

**Comment by why168** [comment]
我加你QQ多少？

**Comment by HappySKT** [comment]
大神 你这个试过用自定义view吗

**Comment by HappySKT** [comment]
534960521

**Comment by why168** [comment]
当然啊，我这个就是用的自定义View啊！
我的View是ImageView而已罢了，你用的自定义View是FrameLayout。
玩法都是差不多一样。

**Comment by HappySKT** [comment]
其实这个问题是解决了，但是具体为什么我还是不太清楚，麻烦有空的时候帮忙看看具体是为什么
